# Site wide configuration

title: Frassati New Haven
description: Description
wordmark: frassati_logo_red.png
logo: # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # default teaser image used in image archive grid
locale: en
# url: http://frassati-new-haven.github.io
# url: frassatinewhaven.org

# Homepage
homepage:
  title: Frassati New Haven
  description: <Description>
  
# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Stefan Avey
  email: info@frassatinewhaven.org
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:

## Social Media
social:
  facebook_username: frassatinewhaven

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
